services:
  - type: web
    name: umltutor-backend
    runtime: node
    rootDir: umltutor-backend
    buildCommand: npm install && npx prisma generate && npx prisma db push
    startCommand: node src/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        fromDatabase:
          name: umltutor-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: CLIENT_URL
        value: https://umltutor.vercel.app
      - key: JWT_EXPIRES_IN
        value: 7d

databases:
  - name: umltutor-db
    plan: free
    databaseName: umltutor
    user: umltutor_user
