"use strict";

const RULE_CATEGORIES = {
  STRUCTURAL: 'structural',
  SEMANTIC: 'semantic',
  CONSISTENCY: 'consistency',
  NAMING: 'naming',
  NLP: 'nlp',
  COMPLETENESS: 'completeness',
  UML_STANDARD: 'uml-standard',
  BEST_PRACTICE: 'best-practice',
};

const DIAGRAM_TYPES = {
  USE_CASE: 'usecase',
  DESCRIPTION: 'description',
  SSD: 'ssd',
  CLASS_DIAGRAM: 'class-diagram',
  SEQUENCE_DIAGRAM: 'sequence-diagram',
  CROSS: 'cross-diagram',
};

const SEVERITIES = {
  ERROR: 'error',
  WARNING: 'warning',
  INFO: 'info',
};

const rules = [
  // ─────────────────────────────────────────────
  // USE CASE DIAGRAM RULES (including new missing rules)
  // ─────────────────────────────────────────────
  {
    id: 'UCD-013',
    code: 'DUPLICATE_ACTOR_NAME',
    name: 'Duplicate Actor Name',
    diagramType: DIAGRAM_TYPES.USE_CASE,
    severity: SEVERITIES.ERROR,
    category: RULE_CATEGORIES.NAMING,
    description: 'Two or more actors share the same name',
    messageTemplate: 'Duplicate Actor name: "{name}". Each actor must have a unique name.',
    dependencies: ['UCD-004'],
    enabled: true,
  },
  {
    id: 'UCD-014',
    code: 'DUPLICATE_USE_CASE_NAME',
    name: 'Duplicate Use Case Name',
    diagramType: DIAGRAM_TYPES.USE_CASE,
    severity: SEVERITIES.ERROR,
    category: RULE_CATEGORIES.NAMING,
    description: 'Two or more use cases share the same name',
    messageTemplate: 'Duplicate Use Case name: "{name}". Each use case must have a unique name.',
    dependencies: ['UCD-008'],
    enabled: true,
  },
  {
    id: 'UCD-015',
    code: 'MULTIPLE_SYSTEM_BOUNDARIES',
    name: 'Multiple System Boundaries',
    diagramType: DIAGRAM_TYPES.USE_CASE,
    severity: SEVERITIES.ERROR,
    category: RULE_CATEGORIES.STRUCTURAL,
    description: 'The diagram contains more than one system boundary',
    messageTemplate: 'Multiple system boundaries detected. A use case diagram should have exactly one system boundary.',
    dependencies: ['UCD-002'],
    enabled: true,
  },
  {
    id: 'UCD-001',
    code: 'DIAGRAM_EMPTY',
    name: 'Diagram Empty',
    diagramType: DIAGRAM_TYPES.USE_CASE,
    severity: SEVERITIES.ERROR,
    category: RULE_CATEGORIES.STRUCTURAL,
    description: 'The use case diagram has no nodes at all',
    messageTemplate: 'Diagram is missing nodes.',
    dependencies: [],
    enabled: true,
  },
  {
    id: 'UCD-002',
    code: 'SYSTEM_BOUNDARY_MISSING',
    name: 'System Boundary Missing',
    diagramType: DIAGRAM_TYPES.USE_CASE,
    severity: SEVERITIES.ERROR,
    category: RULE_CATEGORIES.STRUCTURAL,
    description: 'The diagram has no system boundary element',
    messageTemplate: 'System boundary is missing.',
    dependencies: [],
    enabled: true,
  },
  {
    id: 'UCD-003',
    code: 'SYSTEM_NAME_INVALID',
    name: 'System Name Invalid',
    diagramType: DIAGRAM_TYPES.USE_CASE,
    severity: SEVERITIES.WARNING,
    category: RULE_CATEGORIES.NAMING,
    description: 'The system boundary name is blank, generic (e.g. "System"), or too short',
    messageTemplate: 'System name "{name}" is not valid.',
    dependencies: ['UCD-002'],
    enabled: true,
  },
  {
    id: 'UCD-004',
    code: 'NO_ACTORS',
    name: 'No Actors Defined',
    diagramType: DIAGRAM_TYPES.USE_CASE,
    severity: SEVERITIES.ERROR,
    category: RULE_CATEGORIES.STRUCTURAL,
    description: 'The diagram contains no actor nodes',
    messageTemplate: 'No Actors defined.',
    dependencies: ['UCD-001'],
    enabled: true,
  },
  {
    id: 'UCD-005',
    code: 'ACTOR_NO_NAME',
    name: 'Actor No Name',
    diagramType: DIAGRAM_TYPES.USE_CASE,
    severity: SEVERITIES.ERROR,
    category: RULE_CATEGORIES.NAMING,
    description: 'An actor node has an empty or missing label',
    messageTemplate: 'Actor has no name.',
    dependencies: ['UCD-004'],
    enabled: true,
  },
  {
    id: 'UCD-006',
    code: 'ACTOR_INVALID_NAME',
    name: 'Actor Invalid Name',
    diagramType: DIAGRAM_TYPES.USE_CASE,
    severity: SEVERITIES.ERROR,
    category: RULE_CATEGORIES.NAMING,
    description: 'Actor name contains or equals "System", which is reserved',
    messageTemplate: 'Invalid Actor Name: "{name}". Actor name cannot be "System".',
    dependencies: ['UCD-004'],
    enabled: true,
  },
  {
    id: 'UCD-007',
    code: 'ACTOR_NOT_CONNECTED',
    name: 'Actor Not Connected',
    diagramType: DIAGRAM_TYPES.USE_CASE,
    severity: SEVERITIES.ERROR,
    category: RULE_CATEGORIES.STRUCTURAL,
    description: 'An actor node has no edges to any use case',
    messageTemplate: 'Actor "{name}" is not connected to any Use Case.',
    dependencies: ['UCD-004'],
    enabled: true,
  },
  {
    id: 'UCD-008',
    code: 'NO_USE_CASES',
    name: 'No Use Cases Defined',
    diagramType: DIAGRAM_TYPES.USE_CASE,
    severity: SEVERITIES.ERROR,
    category: RULE_CATEGORIES.STRUCTURAL,
    description: 'The diagram contains no use case nodes',
    messageTemplate: 'No Use Cases defined inside system.',
    dependencies: ['UCD-001'],
    enabled: true,
  },
  {
    id: 'UCD-009',
    code: 'USE_CASE_NO_NAME',
    name: 'Use Case No Name',
    diagramType: DIAGRAM_TYPES.USE_CASE,
    severity: SEVERITIES.ERROR,
    category: RULE_CATEGORIES.NAMING,
    description: 'A use case node has an empty or missing label',
    messageTemplate: 'Use Case has no name.',
    dependencies: ['UCD-008'],
    enabled: true,
  },
  {
    id: 'UCD-010',
    code: 'USE_CASE_INVALID_NAME',
    name: 'Use Case Invalid Name',
    diagramType: DIAGRAM_TYPES.USE_CASE,
    severity: SEVERITIES.ERROR,
    category: RULE_CATEGORIES.NAMING,
    description: 'Use case name must be at least 2 words and start with a verb from the dictionary',
    messageTemplate: 'Invalid Use Case Name: "{name}". Use case name must start with a verb.',
    dependencies: ['UCD-008'],
    enabled: true,
  },
  {
    id: 'UCD-011',
    code: 'USE_CASE_OUTSIDE_BOUNDARY',
    name: 'Use Case Outside Boundary',
    diagramType: DIAGRAM_TYPES.USE_CASE,
    severity: SEVERITIES.ERROR,
    category: RULE_CATEGORIES.STRUCTURAL,
    description: 'A use case node is not a child of the system boundary',
    messageTemplate: 'Use Case "{name}" is outside system boundary.',
    dependencies: ['UCD-002', 'UCD-008'],
    enabled: true,
  },
  {
    id: 'UCD-012',
    code: 'USE_CASE_NOT_CONNECTED',
    name: 'Use Case Not Connected',
    diagramType: DIAGRAM_TYPES.USE_CASE,
    severity: SEVERITIES.WARNING,
    category: RULE_CATEGORIES.STRUCTURAL,
    description: 'A use case node has no edges to any actor',
    messageTemplate: 'Use Case "{name}" is not connected to any Actor.',
    dependencies: ['UCD-008'],
    enabled: true,
  },

  // ─────────────────────────────────────────────
  // USE CASE DESCRIPTION RULES (including new rules)
  // ─────────────────────────────────────────────
  {
    id: 'UCDESC-010',
    code: 'MIN_STEP_COUNT',
    name: 'Minimum Step Count',
    diagramType: DIAGRAM_TYPES.DESCRIPTION,
    severity: SEVERITIES.WARNING,
    category: RULE_CATEGORIES.BEST_PRACTICE,
    description: 'A description main flow should have at least 3 steps to be meaningful',
    messageTemplate: 'Description for "{name}" has only {count} step(s). A main scenario should have at least 3 steps.',
    dependencies: ['UCDESC-001'],
    enabled: true,
  },
  {
    id: 'UCDESC-011',
    code: 'DUPLICATE_STEP',
    name: 'Duplicate Step',
    diagramType: DIAGRAM_TYPES.DESCRIPTION,
    severity: SEVERITIES.WARNING,
    category: RULE_CATEGORIES.STRUCTURAL,
    description: 'Two or more steps in the main flow are identical',
    messageTemplate: 'Step {step} in "{name}" is identical to another step. Steps should be unique.',
    dependencies: ['UCDESC-001'],
    enabled: true,
  },
  {
    id: 'UCDESC-001',
    code: 'NO_USE_CASE_DESCRIPTION',
    name: 'Missing Description',
    diagramType: DIAGRAM_TYPES.DESCRIPTION,
    severity: SEVERITIES.WARNING,
    category: RULE_CATEGORIES.COMPLETENESS,
    description: 'A use case from the diagram has no corresponding description (DEPRECATED: the engine emits DESCRIPTION_NOT_FOUND instead)',
    messageTemplate: 'Use Case "{name}" is missing a description.',
    dependencies: ['UCD-008'],
    enabled: false,
  },
  {
    id: 'UCDESC-002',
    code: 'NO_PRIMARY_ACTOR',
    name: 'Primary Actor Not Set',
    diagramType: DIAGRAM_TYPES.DESCRIPTION,
    severity: SEVERITIES.ERROR,
    category: RULE_CATEGORIES.COMPLETENESS,
    description: 'The primary actor field is blank or set to "Not Set"',
    messageTemplate: 'Primary actor not set in description for "{name}", please set it.',
    dependencies: ['UCDESC-001'],
    enabled: true,
  },
  {
    id: 'UCDESC-003',
    code: 'INVALID_PRIMARY_ACTOR',
    name: 'Primary Actor Not in Diagram',
    diagramType: DIAGRAM_TYPES.DESCRIPTION,
    severity: SEVERITIES.ERROR,
    category: RULE_CATEGORIES.CONSISTENCY,
    description: 'The primary actor name does not match any actor label in the use case diagram',
    messageTemplate: 'Primary Actor "{actor}" in description for "{name}" does not exist in the use case diagram.',
    dependencies: ['UCDESC-002'],
    enabled: true,
  },
  {
    id: 'UCDESC-004',
    code: 'NO_PRECONDITIONS',
    name: 'Precondition Missing',
    diagramType: DIAGRAM_TYPES.DESCRIPTION,
    severity: SEVERITIES.ERROR,
    category: RULE_CATEGORIES.COMPLETENESS,
    description: 'The precondition field is blank or set to "None"',
    messageTemplate: 'Precondition missing in description for "{name}", please define it.',
    dependencies: ['UCDESC-001'],
    enabled: true,
  },
  {
    id: 'UCDESC-005',
    code: 'INVALID_PRECONDITIONS',
    name: 'Invalid Precondition',
    diagramType: DIAGRAM_TYPES.DESCRIPTION,
    severity: SEVERITIES.ERROR,
    category: RULE_CATEGORIES.NLP,
    description: 'The precondition sentence fails validation (too short, no vowel, etc.)',
    messageTemplate: 'Invalid Precondition for "{name}": {error}',
    dependencies: ['UCDESC-004'],
    enabled: true,
  },
  {
    id: 'UCDESC-006',
    code: 'NO_POSTCONDITIONS',
    name: 'Postcondition Missing',
    diagramType: DIAGRAM_TYPES.DESCRIPTION,
    severity: SEVERITIES.ERROR,
    category: RULE_CATEGORIES.COMPLETENESS,
    description: 'The postcondition field is blank or set to "None"',
    messageTemplate: 'Postcondition missing in description for "{name}", please define it.',
    dependencies: ['UCDESC-001'],
    enabled: true,
  },
  {
    id: 'UCDESC-007',
    code: 'INVALID_POSTCONDITIONS',
    name: 'Invalid Postcondition',
    diagramType: DIAGRAM_TYPES.DESCRIPTION,
    severity: SEVERITIES.ERROR,
    category: RULE_CATEGORIES.NLP,
    description: 'The postcondition sentence fails validation',
    messageTemplate: 'Invalid Postcondition for "{name}": {error}',
    dependencies: ['UCDESC-006'],
    enabled: true,
  },
  {
    id: 'UCDESC-008',
    code: 'NO_MAIN_FLOW',
    name: 'Main Flow Missing',
    diagramType: DIAGRAM_TYPES.DESCRIPTION,
    severity: SEVERITIES.WARNING,
    category: RULE_CATEGORIES.COMPLETENESS,
    description: 'The description has no main flow steps',
    messageTemplate: 'Description for "{name}" has no main flow steps.',
    dependencies: ['UCDESC-001'],
    enabled: true,
  },
  {
    id: 'UCDESC-009',
    code: 'INVALID_MAIN_FLOW_STEP',
    name: 'Invalid Main Flow Step',
    diagramType: DIAGRAM_TYPES.DESCRIPTION,
    severity: SEVERITIES.ERROR,
    category: RULE_CATEGORIES.NLP,
    description: 'A main flow step does not form a valid sentence',
    messageTemplate: 'Step {step} in "{name}" is invalid: {error}',
    dependencies: ['UCDESC-008'],
    enabled: true,
  },

  // ─────────────────────────────────────────────
  // SSD RULES
  // ─────────────────────────────────────────────
  {
    id: 'SSD-001',
    code: 'SSD_NOT_FOUND',
    name: 'SSD Not Found',
    diagramType: DIAGRAM_TYPES.SSD,
    severity: SEVERITIES.ERROR,
    category: RULE_CATEGORIES.COMPLETENESS,
    description: 'No SSD data exists for a use case that has a description',
    messageTemplate: 'System Sequence Diagram for "{name}" is not found or empty.',
    dependencies: [],
    enabled: true,
  },
  {
    id: 'SSD-002',
    code: 'INCOMPLETE_SSD',
    name: 'SSD Incomplete',
    diagramType: DIAGRAM_TYPES.SSD,
    severity: SEVERITIES.ERROR,
    category: RULE_CATEGORIES.STRUCTURAL,
    description: 'SSD has fewer than 2 lifelines (need at least Actor + System)',
    messageTemplate: 'SSD for "{name}" is incomplete.',
    dependencies: ['SSD-001'],
    enabled: true,
  },
  {
    id: 'SSD-003',
    code: 'SSD_SEMANTIC_ERROR',
    name: 'SSD Semantic Error',
    diagramType: DIAGRAM_TYPES.SSD,
    severity: SEVERITIES.ERROR,
    category: RULE_CATEGORIES.UML_STANDARD,
    description: 'Generic SSD semantic validation error from ssdValidationService',
    messageTemplate: 'SSD "{name}": {error}',
    dependencies: ['SSD-001'],
    enabled: true,
  },
  {
    id: 'SSD-004',
    code: 'SSD_ACTOR_MISSING',
    name: 'SSD Actor Missing',
    diagramType: DIAGRAM_TYPES.SSD,
    severity: SEVERITIES.ERROR,
    category: RULE_CATEGORIES.UML_STANDARD,
    description: 'No actor participant defined in the SSD lifelines',
    messageTemplate: 'SSD "{name}": At least one Actor participant is required.',
    dependencies: ['SSD-001'],
    enabled: true,
  },
  {
    id: 'SSD-005',
    code: 'SSD_SYSTEM_MISSING',
    name: 'SSD System Missing',
    diagramType: DIAGRAM_TYPES.SSD,
    severity: SEVERITIES.ERROR,
    category: RULE_CATEGORIES.UML_STANDARD,
    description: 'No system participant defined in the SSD lifelines',
    messageTemplate: 'SSD "{name}": Exactly one System participant is typically required.',
    dependencies: ['SSD-001'],
    enabled: true,
  },
  {
    id: 'SSD-006',
    code: 'MISSING_DESCRIPTION_LINK',
    name: 'SSD Missing Description Link',
    diagramType: DIAGRAM_TYPES.SSD,
    severity: SEVERITIES.INFO,
    category: RULE_CATEGORIES.CONSISTENCY,
    description: 'An SSD exists but its corresponding use case description does not',
    messageTemplate: 'Suggestion: Add a description for use case "{name}" to maintain consistency across the model.',
    dependencies: ['SSD-001'],
    enabled: true,
  },
  {
    id: 'SSD-007',
    code: 'SSD_SENDER_NOT_FOUND',
    name: 'SSD Sender Not Found',
    diagramType: DIAGRAM_TYPES.SSD,
    severity: SEVERITIES.ERROR,
    category: RULE_CATEGORIES.UML_STANDARD,
    description: 'A message references a sender lifeline that does not exist',
    messageTemplate: 'Message {index}: Sender participant not found',
    dependencies: ['SSD-001'],
    enabled: true,
  },
  {
    id: 'SSD-008',
    code: 'SSD_RECEIVER_NOT_FOUND',
    name: 'SSD Receiver Not Found',
    diagramType: DIAGRAM_TYPES.SSD,
    severity: SEVERITIES.ERROR,
    category: RULE_CATEGORIES.UML_STANDARD,
    description: 'A message references a receiver lifeline that does not exist',
    messageTemplate: 'Message {index}: Receiver participant not found',
    dependencies: ['SSD-001'],
    enabled: true,
  },
  {
    id: 'SSD-009',
    code: 'SSD_MESSAGE_DIRECTION',
    name: 'SSD Message Direction',
    diagramType: DIAGRAM_TYPES.SSD,
    severity: SEVERITIES.ERROR,
    category: RULE_CATEGORIES.UML_STANDARD,
    description: 'Synchronous messages in SSD should go from Actor to System',
    messageTemplate: 'Message {index}: Synchronous messages in SSD should go from Actor to System',
    dependencies: ['SSD-001'],
    enabled: true,
  },
  {
    id: 'SSD-010',
    code: 'SSD_RETURN_DIRECTION',
    name: 'SSD Return Direction',
    diagramType: DIAGRAM_TYPES.SSD,
    severity: SEVERITIES.ERROR,
    category: RULE_CATEGORIES.UML_STANDARD,
    description: 'Return messages in SSD should go from System to Actor',
    messageTemplate: 'Message {index}: Return messages in SSD should go from System to Actor',
    dependencies: ['SSD-001'],
    enabled: true,
  },
  {
    id: 'SSD-011',
    code: 'SSD_CREATE_DELETE_ACTOR',
    name: 'SSD Create/Delete Actor',
    diagramType: DIAGRAM_TYPES.SSD,
    severity: SEVERITIES.ERROR,
    category: RULE_CATEGORIES.UML_STANDARD,
    description: 'Actors cannot be created or deleted in an SSD',
    messageTemplate: 'Message {index}: Actors cannot be created or deleted',
    dependencies: ['SSD-001'],
    enabled: true,
  },
  {
    id: 'SSD-012',
    code: 'SSD_PARTICIPANT_MISMATCH',
    name: 'SSD Participant Mismatch',
    diagramType: DIAGRAM_TYPES.SSD,
    severity: SEVERITIES.ERROR,
    category: RULE_CATEGORIES.UML_STANDARD,
    description: 'A message references a participant that does not exist in the lifeline list',
    messageTemplate: 'Message {index}: Sender or Receiver participant not found',
    dependencies: ['SSD-001'],
    enabled: true,
  },

  // ─────────────────────────────────────────────
  // SSD-DESCRIPTION CONSISTENCY RULES
  // ─────────────────────────────────────────────
  {
    id: 'SSDCONS-001',
    code: 'SSD_CONSISTENCY_ACTOR_MISMATCH',
    name: 'SSD Actor Mismatch',
    diagramType: DIAGRAM_TYPES.CROSS,
    severity: SEVERITIES.ERROR,
    category: RULE_CATEGORIES.CONSISTENCY,
    description: 'The first actor in the SSD does not match the description primary actor',
    messageTemplate: 'SSD Consistency error: Started with Actor "{actor}", but description defines "{descActor}".',
    dependencies: ['SSD-001', 'UCDESC-001'],
    enabled: true,
  },
  {
    id: 'SSDCONS-002',
    code: 'SSD_CONSISTENCY_ORDER_MISMATCH',
    name: 'SSD Order Mismatch',
    diagramType: DIAGRAM_TYPES.CROSS,
    severity: SEVERITIES.ERROR,
    category: RULE_CATEGORIES.CONSISTENCY,
    description: 'An SSD message appears out of order relative to the description step sequence',
    messageTemplate: 'Message Sequence Mismatch',
    dependencies: ['SSD-001', 'UCDESC-001'],
    enabled: true,
  },
  {
    id: 'SSDCONS-003',
    code: 'SSD_CONSISTENCY_SOURCE_MISMATCH',
    name: 'SSD Source Mismatch',
    diagramType: DIAGRAM_TYPES.CROSS,
    severity: SEVERITIES.WARNING,
    category: RULE_CATEGORIES.CONSISTENCY,
    description: 'A system action step has a message originating from an actor instead of the system',
    messageTemplate: 'Source Lifeline Mismatch',
    dependencies: ['SSD-001', 'UCDESC-001'],
    enabled: true,
  },
  {
    id: 'SSDCONS-004',
    code: 'SSD_CONSISTENCY_SHOULD_BE_SELF_LOOP',
    name: 'SSD Should Be Self-Loop',
    diagramType: DIAGRAM_TYPES.CROSS,
    severity: SEVERITIES.WARNING,
    category: RULE_CATEGORIES.UML_STANDARD,
    description: 'An internal system operation step should be a self-loop message on the system lifeline',
    messageTemplate: 'Expected Self-loop Message',
    dependencies: ['SSD-001', 'UCDESC-001'],
    enabled: true,
  },
  {
    id: 'SSDCONS-005',
    code: 'SSD_CONSISTENCY_SHOULD_BE_EXTERNAL',
    name: 'SSD Should Be External Response',
    diagramType: DIAGRAM_TYPES.CROSS,
    severity: SEVERITIES.WARNING,
    category: RULE_CATEGORIES.UML_STANDARD,
    description: 'A system output step should be a System-to-Actor message, not a self-loop',
    messageTemplate: 'Expected System → Actor Message',
    dependencies: ['SSD-001', 'UCDESC-001'],
    enabled: true,
  },
  {
    id: 'SSDCONS-006',
    code: 'SSD_CONSISTENCY_EXTERNAL_TARGET',
    name: 'SSD External Target Mismatch',
    diagramType: DIAGRAM_TYPES.CROSS,
    severity: SEVERITIES.WARNING,
    category: RULE_CATEGORIES.CONSISTENCY,
    description: 'A system response message targets a non-actor lifeline',
    messageTemplate: 'Response Should Target Actor',
    dependencies: ['SSD-001', 'UCDESC-001'],
    enabled: true,
  },
  {
    id: 'SSDCONS-007',
    code: 'SSD_CONSISTENCY_TARGET_MISMATCH',
    name: 'SSD Target Lifeline Mismatch',
    diagramType: DIAGRAM_TYPES.CROSS,
    severity: SEVERITIES.WARNING,
    category: RULE_CATEGORIES.CONSISTENCY,
    description: 'A non-return message targets a non-system lifeline',
    messageTemplate: 'Target Lifeline Mismatch',
    dependencies: ['SSD-001', 'UCDESC-001'],
    enabled: true,
  },
  {
    id: 'SSDCONS-008',
    code: 'SSD_CONSISTENCY_TYPE_MISMATCH',
    name: 'SSD Message Type Mismatch',
    diagramType: DIAGRAM_TYPES.CROSS,
    severity: SEVERITIES.WARNING,
    category: RULE_CATEGORIES.UML_STANDARD,
    description: 'A system action step has a call message instead of a return',
    messageTemplate: 'Message Type Mismatch',
    dependencies: ['SSD-001', 'UCDESC-001'],
    enabled: true,
  },
  {
    id: 'SSDCONS-009',
    code: 'SSD_CONSISTENCY_NAME_GUIDANCE',
    name: 'SSD Message Name Guidance',
    diagramType: DIAGRAM_TYPES.CROSS,
    severity: SEVERITIES.WARNING,
    category: RULE_CATEGORIES.BEST_PRACTICE,
    description: 'An SSD message name lacks standard method formatting (no parameters)',
    messageTemplate: 'Message Name Guidance',
    dependencies: ['SSD-001', 'UCDESC-001'],
    enabled: true,
  },
  {
    id: 'SSDCONS-010',
    code: 'SSD_CONSISTENCY_MISSING_MESSAGE',
    name: 'SSD Missing Message',
    diagramType: DIAGRAM_TYPES.CROSS,
    severity: SEVERITIES.ERROR,
    category: RULE_CATEGORIES.CONSISTENCY,
    description: 'A description step has no mapped message in the SSD',
    messageTemplate: 'Missing SSD Message',
    dependencies: ['SSD-001', 'UCDESC-001'],
    enabled: true,
  },
  {
    id: 'SSDCONS-011',
    code: 'SSD_CONSISTENCY_EXTRA_MESSAGE',
    name: 'SSD Extra Message',
    diagramType: DIAGRAM_TYPES.CROSS,
    severity: SEVERITIES.ERROR,
    category: RULE_CATEGORIES.CONSISTENCY,
    description: 'An SSD message has no corresponding step in the description',
    messageTemplate: 'Extra SSD Message',
    dependencies: ['SSD-001', 'UCDESC-001'],
    enabled: true,
  },

  // ─────────────────────────────────────────────
  // CROSS-DIAGRAM MAPPING RULES
  // ─────────────────────────────────────────────
  {
    id: 'MAP-001',
    code: 'MAPPING_MISMATCH',
    name: 'Mapping Mismatch',
    diagramType: DIAGRAM_TYPES.CROSS,
    severity: SEVERITIES.WARNING,
    category: RULE_CATEGORIES.CONSISTENCY,
    description: 'An SSD exists for a use case that has no description',
    messageTemplate: 'Mapping Error: SSD is modeling "{name}", but its corresponding Description is missing.',
    dependencies: [],
    enabled: true,
  },
  {
    id: 'MAP-002',
    code: 'MAPPING_INCOMPLETE',
    name: 'Mapping Incomplete',
    diagramType: DIAGRAM_TYPES.CROSS,
    severity: SEVERITIES.INFO,
    category: RULE_CATEGORIES.COMPLETENESS,
    description: 'A description exists but no SSD has been created for the same use case',
    messageTemplate: 'Description exists, but System Sequence Diagram has not been started yet.',
    dependencies: [],
    enabled: true,
  },
  {
    id: 'MAP-003',
    code: 'CLASS_DIAGRAM_MISSING',
    name: 'Class Diagram Missing',
    diagramType: DIAGRAM_TYPES.CROSS,
    severity: SEVERITIES.INFO,
    category: RULE_CATEGORIES.COMPLETENESS,
    description: 'Descriptions and SSDs exist but no class diagram has been started',
    messageTemplate: 'Description and SSD exist for "{name}", but Class Diagram has not been started.',
    dependencies: [],
    enabled: true,
  },
  {
    id: 'MAP-005',
    code: 'SEQUENCE_WITHOUT_DESCRIPTION',
    name: 'Sequence Without Description',
    diagramType: DIAGRAM_TYPES.CROSS,
    severity: SEVERITIES.WARNING,
    category: RULE_CATEGORIES.CONSISTENCY,
    description: 'A sequence diagram exists but its use case has no description',
    messageTemplate: 'Sequence Diagram exists but Description is missing.',
    dependencies: [],
    enabled: true,
  },
  {
    id: 'MAP-006a',
    code: 'SEQ_EXTRA_MESSAGES',
    name: 'Sequence Extra Messages vs SSD',
    diagramType: DIAGRAM_TYPES.CROSS,
    severity: SEVERITIES.INFO,
    category: RULE_CATEGORIES.CONSISTENCY,
    description: 'The sequence diagram has significantly more non-return messages than the SSD',
    messageTemplate: 'Sequence Diagram has significantly more interactions ({seqCount}) than SSD ({ssdCount}).',
    dependencies: [],
    enabled: true,
  },
  {
    id: 'MAP-006',
    code: 'SEQ_FEWER_THAN_SSD',
    name: 'Sequence Fewer Messages Than SSD',
    diagramType: DIAGRAM_TYPES.CROSS,
    severity: SEVERITIES.WARNING,
    category: RULE_CATEGORIES.CONSISTENCY,
    description: 'The sequence diagram has fewer non-return messages than the corresponding SSD',
    messageTemplate: 'Sequence Diagram has fewer interactions ({seqCount}) than SSD ({ssdCount}).',
    dependencies: [],
    enabled: true,
  },
  {
    id: 'MAP-007',
    code: 'SEQUENCE_DIAGRAMS_INCOMPLETE',
    name: 'Sequence Diagrams Incomplete',
    diagramType: DIAGRAM_TYPES.CROSS,
    severity: SEVERITIES.INFO,
    category: RULE_CATEGORIES.COMPLETENESS,
    description: 'Class diagram exists but no sequence diagrams were found',
    messageTemplate: 'Class Diagram exists but no Sequence Diagrams were found.',
    dependencies: [],
    enabled: true,
  },

  // ─────────────────────────────────────────────
  // CLASS DIAGRAM RULES (including new rules)
  // ─────────────────────────────────────────────
  {
    id: 'CD-007',
    code: 'DUPLICATE_CLASS_NAME',
    name: 'Duplicate Class Name',
    diagramType: DIAGRAM_TYPES.CLASS_DIAGRAM,
    severity: SEVERITIES.ERROR,
    category: RULE_CATEGORIES.NAMING,
    description: 'Two or more classes share the same name',
    messageTemplate: 'Duplicate Class name: "{name}". Each class must have a unique name.',
    dependencies: ['CD-002'],
    enabled: true,
  },
  {
    id: 'CD-001',
    code: 'CLASS_DIAGRAM_EMPTY',
    name: 'Class Diagram Empty',
    diagramType: DIAGRAM_TYPES.CLASS_DIAGRAM,
    severity: SEVERITIES.ERROR,
    category: RULE_CATEGORIES.STRUCTURAL,
    description: 'The class diagram has no nodes at all',
    messageTemplate: 'Class Diagram is empty.',
    dependencies: [],
    enabled: true,
  },
  {
    id: 'CD-002',
    code: 'NO_CLASSES',
    name: 'No Classes in Class Diagram',
    diagramType: DIAGRAM_TYPES.CLASS_DIAGRAM,
    severity: SEVERITIES.ERROR,
    category: RULE_CATEGORIES.STRUCTURAL,
    description: 'The class diagram has nodes but none are class or interface types',
    messageTemplate: 'No classes or interfaces defined in the Class Diagram.',
    dependencies: ['CD-001'],
    enabled: true,
  },
  {
    id: 'CD-003',
    code: 'CLASS_NAME_PLACEHOLDER',
    name: 'Class Name Placeholder',
    diagramType: DIAGRAM_TYPES.CLASS_DIAGRAM,
    severity: SEVERITIES.ERROR,
    category: RULE_CATEGORIES.NAMING,
    description: 'A class uses a placeholder name like "NewClass", "Class", "Untitled"',
    messageTemplate: 'Class "{name}" uses a placeholder name.',
    dependencies: ['CD-002'],
    enabled: true,
  },
  {
    id: 'CD-004',
    code: 'NO_METHODS',
    name: 'No Methods in Class Diagram',
    diagramType: DIAGRAM_TYPES.CLASS_DIAGRAM,
    severity: SEVERITIES.WARNING,
    category: RULE_CATEGORIES.COMPLETENESS,
    description: 'No operations/methods defined on any class',
    messageTemplate: 'No operations/methods defined on any class.',
    dependencies: ['CD-002'],
    enabled: true,
  },
  {
    id: 'CD-005',
    code: 'CLASS_METHOD_MISSING_FOR_SSD',
    name: 'Class Method Missing for SSD',
    diagramType: DIAGRAM_TYPES.CROSS,
    severity: SEVERITIES.WARNING,
    category: RULE_CATEGORIES.CONSISTENCY,
    description: 'An SSD message name has no matching method in any class (DEPRECATED: the engine emits MISSING_CLASS_OPERATION instead)',
    messageTemplate: 'SSD message "{msg}" has no matching operation in the Class Diagram.',
    dependencies: ['CD-002'],
    enabled: false,
  },
  {
    id: 'CD-006',
    code: 'CLASS_ENTITY_SUGGESTION',
    name: 'Class Entity Suggestion',
    diagramType: DIAGRAM_TYPES.CROSS,
    severity: SEVERITIES.INFO,
    category: RULE_CATEGORIES.BEST_PRACTICE,
    description: 'A noun from the description scenario steps could be a class',
    messageTemplate: 'Consider a class for "{noun}" (from "{name}" scenario).',
    dependencies: ['CD-002'],
    enabled: true,
  },

  // ─────────────────────────────────────────────
  // SEQUENCE DIAGRAM RULES (including new rules)
  // ─────────────────────────────────────────────
  {
    id: 'SEQ-008',
    code: 'DUPLICATE_LIFELINE',
    name: 'Duplicate Lifeline',
    diagramType: DIAGRAM_TYPES.SEQUENCE_DIAGRAM,
    severity: SEVERITIES.WARNING,
    category: RULE_CATEGORIES.STRUCTURAL,
    description: 'Two lifelines in the same sequence diagram have the same label',
    messageTemplate: 'Duplicate lifeline "{label}" in Sequence Diagram for "{name}".',
    dependencies: ['SEQ-002'],
    enabled: true,
  },
  {
    id: 'SEQ-009',
    code: 'SEQUENCE_MISSING_RETURN',
    name: 'Sequence Missing Return',
    diagramType: DIAGRAM_TYPES.SEQUENCE_DIAGRAM,
    severity: SEVERITIES.WARNING,
    category: RULE_CATEGORIES.UML_STANDARD,
    description: 'A synchronous call message has no matching return message',
    messageTemplate: 'Synchronous call "{msg}" in Sequence Diagram for "{name}" has no matching return message.',
    dependencies: ['SEQ-002'],
    enabled: true,
  },
  {
    id: 'SEQ-001',
    code: 'SEQUENCE_DIAGRAM_MISSING',
    name: 'Sequence Diagram Missing',
    diagramType: DIAGRAM_TYPES.SEQUENCE_DIAGRAM,
    severity: SEVERITIES.ERROR,
    category: RULE_CATEGORIES.COMPLETENESS,
    description: 'No sequence diagram data exists for a use case that has a description',
    messageTemplate: 'Sequence Diagram for "{name}" is missing.',
    dependencies: [],
    enabled: true,
  },
  {
    id: 'SEQ-002',
    code: 'SEQUENCE_DIAGRAM_EMPTY',
    name: 'Sequence Diagram Empty',
    diagramType: DIAGRAM_TYPES.SEQUENCE_DIAGRAM,
    severity: SEVERITIES.ERROR,
    category: RULE_CATEGORIES.STRUCTURAL,
    description: 'The sequence diagram has no lifelines',
    messageTemplate: 'Sequence Diagram for "{name}" is empty.',
    dependencies: ['SEQ-001'],
    enabled: true,
  },
  {
    id: 'SEQ-003',
    code: 'SEQUENCE_INCOMPLETE',
    name: 'Sequence Diagram Incomplete',
    diagramType: DIAGRAM_TYPES.SEQUENCE_DIAGRAM,
    severity: SEVERITIES.ERROR,
    category: RULE_CATEGORIES.STRUCTURAL,
    description: 'Sequence diagram has fewer than 2 lifelines',
    messageTemplate: 'Sequence Diagram for "{name}" needs at least two lifelines.',
    dependencies: ['SEQ-002'],
    enabled: true,
  },
  {
    id: 'SEQ-004',
    code: 'SEQUENCE_NO_MESSAGES',
    name: 'Sequence Diagram No Messages',
    diagramType: DIAGRAM_TYPES.SEQUENCE_DIAGRAM,
    severity: SEVERITIES.ERROR,
    category: RULE_CATEGORIES.STRUCTURAL,
    description: 'Sequence diagram has lifelines but no messages',
    messageTemplate: 'Sequence Diagram for "{name}" has no messages.',
    dependencies: ['SEQ-002'],
    enabled: true,
  },
  {
    id: 'SEQ-005',
    code: 'SEQUENCE_LIFELINE_NOT_IN_CLASS_DIAGRAM',
    name: 'Sequence Lifeline Not in Class Diagram',
    diagramType: DIAGRAM_TYPES.CROSS,
    severity: SEVERITIES.WARNING,
    category: RULE_CATEGORIES.CONSISTENCY,
    description: 'A sequence diagram lifeline does not match any class in the class diagram (DEPRECATED: the engine emits SEQUENCE_OBJECT_NOT_DEFINED instead)',
    messageTemplate: 'Lifeline "{label}" does not match any class in the Class Diagram.',
    dependencies: ['CD-002'],
    enabled: false,
  },
  {
    id: 'SEQ-006',
    code: 'SEQUENCE_MESSAGE_NOT_IN_CLASS',
    name: 'Sequence Message Not in Class',
    diagramType: DIAGRAM_TYPES.CROSS,
    severity: SEVERITIES.WARNING,
    category: RULE_CATEGORIES.CONSISTENCY,
    description: 'A sequence message name is not declared on any class in the class diagram (DEPRECATED: the engine emits SEQUENCE_OPERATION_NOT_DEFINED instead)',
    messageTemplate: 'Message "{msg}" is not declared on any class in the Class Diagram.',
    dependencies: ['CD-002'],
    enabled: false,
  },
  {
    id: 'SEQ-007',
    code: 'SEQUENCE_MISSING_SSD_MESSAGE',
    name: 'Sequence Missing SSD Message',
    diagramType: DIAGRAM_TYPES.CROSS,
    severity: SEVERITIES.ERROR,
    category: RULE_CATEGORIES.CONSISTENCY,
    description: 'An SSD message is not reflected in the corresponding sequence diagram',
    messageTemplate: 'SSD message "{msg}" is not reflected in Sequence Diagram for "{name}".',
    dependencies: ['SSD-001'],
    enabled: true,
  },
  {
    id: 'SEQCONS-001',
    code: 'SEQ_CONSISTENCY_ACTOR_MISMATCH',
    name: 'Sequence Actor Mismatch',
    diagramType: DIAGRAM_TYPES.CROSS,
    severity: SEVERITIES.ERROR,
    category: RULE_CATEGORIES.CONSISTENCY,
    description: 'The first actor lifeline in the sequence diagram does not match the description primary actor',
    messageTemplate: 'Sequence first actor lifeline "{actor}" does not match description primary actor "{descActor}".',
    dependencies: ['SEQ-001', 'UCDESC-001'],
    enabled: true,
  },
  {
    id: 'SEQCONS-002',
    code: 'SEQ_CONSISTENCY_MISSING_MESSAGE',
    name: 'Sequence Missing Message for Step',
    diagramType: DIAGRAM_TYPES.CROSS,
    severity: SEVERITIES.ERROR,
    category: RULE_CATEGORIES.CONSISTENCY,
    description: 'A description step has no mapped message in the sequence diagram',
    messageTemplate: 'Missing sequence message for Step {step} in "{name}".',
    dependencies: ['SEQ-001', 'UCDESC-001'],
    enabled: true,
  },
  {
    id: 'SEQCONS-003',
    code: 'SEQ_CONSISTENCY_EXTRA_MESSAGE',
    name: 'Sequence Extra Message',
    diagramType: DIAGRAM_TYPES.CROSS,
    severity: SEVERITIES.ERROR,
    category: RULE_CATEGORIES.CONSISTENCY,
    description: 'A sequence message has no corresponding step in the description',
    messageTemplate: 'Extra sequence message "{msg}" in "{name}" is not mapped to the Main Success Scenario.',
    dependencies: ['SEQ-001', 'UCDESC-001'],
    enabled: true,
  },

  // ─────────────────────────────────────────────
  // ENGINE-EMITTED RULES NOT PREVIOUSLY REGISTERED
  // (reconciled against checkingEngine.js / ssdValidationService.js)
  // ─────────────────────────────────────────────
  {
    id: 'UCDESC-012',
    code: 'DESCRIPTION_NOT_FOUND',
    name: 'Description Not Found',
    diagramType: DIAGRAM_TYPES.DESCRIPTION,
    severity: SEVERITIES.ERROR,
    category: RULE_CATEGORIES.COMPLETENESS,
    description: 'A use case in the diagram has no corresponding description (replaces deprecated UCDESC-001)',
    messageTemplate: 'Use Case Description not found for "{name}".',
    dependencies: ['UCD-008'],
    enabled: true,
  },
  {
    id: 'UCDESC-013',
    code: 'NO_TITLE',
    name: 'Description Title Missing',
    diagramType: DIAGRAM_TYPES.DESCRIPTION,
    severity: SEVERITIES.ERROR,
    category: RULE_CATEGORIES.COMPLETENESS,
    description: 'The use case description has no title / useCaseName',
    messageTemplate: 'Use Case title is missing in description for "{name}".',
    dependencies: ['UCD-008'],
    enabled: true,
  },
  {
    id: 'UCDESC-014',
    code: 'USE_CASE_NAME_MISMATCH',
    name: 'Use Case Name Mismatch',
    diagramType: DIAGRAM_TYPES.DESCRIPTION,
    severity: SEVERITIES.WARNING,
    category: RULE_CATEGORIES.CONSISTENCY,
    description: 'The description name does not exactly match the diagram use case name',
    messageTemplate: 'Description name "{descName}" does not match diagram name "{name}".',
    dependencies: ['UCD-008'],
    enabled: true,
  },
  {
    id: 'UCDESC-015',
    code: 'PRIMARY_ACTOR_NOT_CONNECTED',
    name: 'Primary Actor Not Connected',
    diagramType: DIAGRAM_TYPES.DESCRIPTION,
    severity: SEVERITIES.WARNING,
    category: RULE_CATEGORIES.CONSISTENCY,
    description: 'The primary actor exists in the diagram but is not associated with the use case',
    messageTemplate: 'Primary Actor "{actor}" is not connected to Use Case "{name}" in the diagram.',
    dependencies: ['UCDESC-002', 'UCDESC-003'],
    enabled: true,
  },
  {
    id: 'UCDESC-016',
    code: 'EMPTY_MAIN_FLOW_STEP',
    name: 'Empty Main Flow Step',
    diagramType: DIAGRAM_TYPES.DESCRIPTION,
    severity: SEVERITIES.WARNING,
    category: RULE_CATEGORIES.COMPLETENESS,
    description: 'A main flow step has a blank or whitespace-only action',
    messageTemplate: 'Step {step} in "{name}" is empty.',
    dependencies: ['UCDESC-008'],
    enabled: true,
  },
  {
    id: 'UCDESC-017',
    code: 'ALT_FLOW_INVALID_RELATED_STEP',
    name: 'Alternative Flow Invalid Related Step',
    diagramType: DIAGRAM_TYPES.DESCRIPTION,
    severity: SEVERITIES.ERROR,
    category: RULE_CATEGORIES.CONSISTENCY,
    description: 'An alternative flow references a main-flow step number that does not exist',
    messageTemplate: 'Alternative flow references step {step} which does not exist in the main flow.',
    dependencies: ['UCDESC-008'],
    enabled: true,
  },
  {
    id: 'UCDESC-018',
    code: 'ALT_FLOW_EMPTY_CONDITION',
    name: 'Alternative Flow Empty Condition',
    diagramType: DIAGRAM_TYPES.DESCRIPTION,
    severity: SEVERITIES.ERROR,
    category: RULE_CATEGORIES.COMPLETENESS,
    description: 'An alternative flow is missing its trigger condition',
    messageTemplate: 'Alternative flow has no condition.',
    dependencies: ['UCDESC-008'],
    enabled: true,
  },
  {
    id: 'UCDESC-019',
    code: 'ALT_FLOW_EMPTY_RESPONSE',
    name: 'Alternative Flow Empty Response',
    diagramType: DIAGRAM_TYPES.DESCRIPTION,
    severity: SEVERITIES.ERROR,
    category: RULE_CATEGORIES.COMPLETENESS,
    description: 'An alternative flow is missing its system response',
    messageTemplate: 'Alternative flow has no system response.',
    dependencies: ['UCDESC-008'],
    enabled: true,
  },
  {
    id: 'UCDESC-020',
    code: 'ALT_FLOW_INVALID_SENTENCE',
    name: 'Alternative Flow Invalid Sentence',
    diagramType: DIAGRAM_TYPES.DESCRIPTION,
    severity: SEVERITIES.ERROR,
    category: RULE_CATEGORIES.NLP,
    description: 'An alternative flow condition or response does not form a valid sentence',
    messageTemplate: 'Alternative flow has an invalid sentence: {error}',
    dependencies: ['UCDESC-008'],
    enabled: true,
  },
  {
    id: 'SSD-013',
    code: 'SSD_OBJECT_NOT_ALLOWED',
    name: 'SSD Object Lifeline Not Allowed',
    diagramType: DIAGRAM_TYPES.SSD,
    severity: SEVERITIES.ERROR,
    category: RULE_CATEGORIES.UML_STANDARD,
    description: 'An SSD contains a non-Actor, non-System (object) lifeline',
    messageTemplate: 'Object lifeline "{label}" is not allowed in a System Sequence Diagram.',
    dependencies: ['SSD-001'],
    enabled: true,
  },
  {
    id: 'SSD-014',
    code: 'SSD_SEMANTIC_MISSING_MESSAGE',
    name: 'SSD Semantic Missing Message',
    diagramType: DIAGRAM_TYPES.SSD,
    severity: SEVERITIES.WARNING,
    category: RULE_CATEGORIES.CONSISTENCY,
    description: 'A description main-flow step has no semantically matching SSD message',
    messageTemplate: 'Step "{step}" in "{name}" has no semantically matching SSD message.',
    dependencies: ['SSD-001'],
    enabled: true,
  },
  {
    id: 'SSD-015',
    code: 'SSD_SEMANTIC_UNUSED_MESSAGE',
    name: 'SSD Semantic Unused Message',
    diagramType: DIAGRAM_TYPES.SSD,
    severity: SEVERITIES.INFO,
    category: RULE_CATEGORIES.CONSISTENCY,
    description: 'An SSD message does not semantically match any main-flow step',
    messageTemplate: 'SSD message "{msg}" in "{name}" does not semantically match any main-flow step.',
    dependencies: ['SSD-001'],
    enabled: true,
  },
  {
    id: 'SSD-016',
    code: 'SSD_MULTIPLE_SYSTEMS',
    name: 'SSD Multiple System Participants',
    diagramType: DIAGRAM_TYPES.SSD,
    severity: SEVERITIES.ERROR,
    category: RULE_CATEGORIES.UML_STANDARD,
    description: 'An SSD contains more than one System lifeline; exactly one System participant is required',
    messageTemplate: 'SSD contains {count} System lifelines; exactly one System participant is required.',
    dependencies: ['SSD-001'],
    enabled: true,
  },
  {
    id: 'SSD-017',
    code: 'SSD_DUPLICATE_MESSAGE',
    name: 'SSD Duplicate Message',
    diagramType: DIAGRAM_TYPES.SSD,
    severity: SEVERITIES.WARNING,
    category: RULE_CATEGORIES.BEST_PRACTICE,
    description: 'An SSD contains duplicate message names',
    messageTemplate: 'Message {index}: Duplicate message name "{name}" appears multiple times in the SSD.',
    dependencies: ['SSD-001'],
    enabled: true,
  },
  {
    id: 'MAP-008',
    code: 'DESCRIPTION_ORPHAN',
    name: 'Description Orphan',
    diagramType: DIAGRAM_TYPES.CROSS,
    severity: SEVERITIES.WARNING,
    category: RULE_CATEGORIES.CONSISTENCY,
    description: 'A description is not linked to any use case in the diagram',
    messageTemplate: 'Description "{name}" is not linked to any use case in the diagram.',
    dependencies: ['UCD-008'],
    enabled: true,
  },
  {
    id: 'CD-008',
    code: 'MISSING_CLASS_OPERATION',
    name: 'Missing Class Operation for SSD',
    diagramType: DIAGRAM_TYPES.CLASS_DIAGRAM,
    severity: SEVERITIES.ERROR,
    category: RULE_CATEGORIES.CONSISTENCY,
    description: 'An SSD message has no corresponding operation in the class diagram (replaces deprecated CD-005)',
    messageTemplate: 'SSD function "{msg}" has no corresponding operation in the Class Diagram.',
    dependencies: ['CD-002'],
    enabled: true,
  },
  {
    id: 'CD-009',
    code: 'CLASS_OPERATION_SEMANTIC_MATCH',
    name: 'Class Operation Partial Semantic Match',
    diagramType: DIAGRAM_TYPES.CLASS_DIAGRAM,
    severity: SEVERITIES.WARNING,
    category: RULE_CATEGORIES.CONSISTENCY,
    description: 'An SSD message only partially matches a class operation name',
    messageTemplate: 'SSD message "{msg}" partially matches operation "{op}".',
    dependencies: ['CD-002'],
    enabled: true,
  },
  {
    id: 'CD-010',
    code: 'CLASS_RESPONSIBILITY_WARNING',
    name: 'Class Responsibility Placement Warning',
    diagramType: DIAGRAM_TYPES.CLASS_DIAGRAM,
    severity: SEVERITIES.INFO,
    category: RULE_CATEGORIES.BEST_PRACTICE,
    description: 'Deprecated — replaced by CD-011 CLASS_RESPONSIBILITY_MISMATCH (general, evidence-based responsibility detection for any domain)',
    messageTemplate: 'Operation "{op}" may be more appropriately associated with a Payment class/service.',
    dependencies: ['CD-002'],
    enabled: false,
  },
  {
    id: 'CD-011',
    code: 'CLASS_RESPONSIBILITY_MISMATCH',
    name: 'Class Responsibility Mismatch',
    diagramType: DIAGRAM_TYPES.CLASS_DIAGRAM,
    severity: SEVERITIES.INFO,
    category: RULE_CATEGORIES.CONSISTENCY,
    description: 'An operation is owned by a class that does not semantically match the use case context',
    messageTemplate: 'Operation "{op}" is owned by "{owner}", but semantically relates to class "{suggested}".',
    dependencies: ['CD-002'],
    enabled: true,
  },
  {
    id: 'CD-012',
    code: 'MISSING_CLASS',
    name: 'Missing Class for SSD Operation',
    diagramType: DIAGRAM_TYPES.CLASS_DIAGRAM,
    severity: SEVERITIES.ERROR,
    category: RULE_CATEGORIES.CONSISTENCY,
    description: 'An SSD operation has no corresponding class defined in the class diagram',
    messageTemplate: 'SSD operation "{op}" in "{uc}" has no corresponding class in the Class Diagram.',
    dependencies: ['CD-002'],
    enabled: true,
  },
  {
    id: 'CD-013',
    code: 'CLASS_PARAMETER_MISMATCH',
    name: 'Class Operation Parameter Mismatch',
    diagramType: DIAGRAM_TYPES.CLASS_DIAGRAM,
    severity: SEVERITIES.WARNING,
    category: RULE_CATEGORIES.CONSISTENCY,
    description: 'An SSD message declares parameters that do not align with the class operation signature',
    messageTemplate: 'SSD operation "{msg}" parameters do not match class operation "{op}".',
    dependencies: ['CD-002'],
    enabled: true,
  },
  {
    id: 'CD-014',
    code: 'CLASS_RETURN_TYPE_MISSING',
    name: 'Class Operation Missing Return Type',
    diagramType: DIAGRAM_TYPES.CLASS_DIAGRAM,
    severity: SEVERITIES.WARNING,
    category: RULE_CATEGORIES.COMPLETENESS,
    description: 'An operation that semantically queries/validates data declares no return type',
    messageTemplate: 'Operation "{op}" performs "{msg}" but declares no return type.',
    dependencies: ['CD-002'],
    enabled: true,
  },
  {
    id: 'CD-015',
    code: 'CLASS_PARAMETER_TYPE_MISSING',
    name: 'Class Parameter Type Missing',
    diagramType: DIAGRAM_TYPES.CLASS_DIAGRAM,
    severity: SEVERITIES.WARNING,
    category: RULE_CATEGORIES.COMPLETENESS,
    description: 'A class operation declares parameters without explicit types',
    messageTemplate: 'Parameters [{params}] on "{op}" are missing explicit types.',
    dependencies: ['CD-002'],
    enabled: true,
  },
  {
    id: 'CD-016',
    code: 'CLASS_METHOD_VISIBILITY',
    name: 'Class Method Visibility Invalid',
    diagramType: DIAGRAM_TYPES.CLASS_DIAGRAM,
    severity: SEVERITIES.WARNING,
    category: RULE_CATEGORIES.UML_STANDARD,
    description: 'An operation invoked by an actor is declared private or protected',
    messageTemplate: 'Operation "{op}" is not public but is invoked by the actor.',
    dependencies: ['CD-002'],
    enabled: true,
  },
  {
    id: 'CD-017',
    code: 'CLASS_NAME_INVALID',
    name: 'Invalid Class Name',
    diagramType: DIAGRAM_TYPES.CLASS_DIAGRAM,
    severity: SEVERITIES.WARNING,
    category: RULE_CATEGORIES.NAMING,
    description: 'A class name does not follow UML PascalCase conventions',
    messageTemplate: 'Class name "{name}" is not a valid UML class name.',
    dependencies: ['CD-002'],
    enabled: true,
  },
  {
    id: 'CD-018',
    code: 'CLASS_ATTRIBUTE_TYPE_MISSING',
    name: 'Class Attribute Type Missing',
    diagramType: DIAGRAM_TYPES.CLASS_DIAGRAM,
    severity: SEVERITIES.WARNING,
    category: RULE_CATEGORIES.COMPLETENESS,
    description: 'A class attribute is declared without an explicit type',
    messageTemplate: 'Attribute "{attr}" on class "{cls}" has no declared type.',
    dependencies: ['CD-002'],
    enabled: true,
  },
  {
    id: 'CD-019',
    code: 'CLASS_ATTRIBUTE_VISIBILITY',
    name: 'Class Attribute Visibility Missing',
    diagramType: DIAGRAM_TYPES.CLASS_DIAGRAM,
    severity: SEVERITIES.INFO,
    category: RULE_CATEGORIES.UML_STANDARD,
    description: 'A class attribute is declared without a visibility marker',
    messageTemplate: 'Attribute "{attr}" on class "{cls}" has no visibility marker.',
    dependencies: ['CD-002'],
    enabled: true,
  },
  {
    id: 'CD-020',
    code: 'CLASS_DUPLICATE_METHOD',
    name: 'Duplicate Class Operation',
    diagramType: DIAGRAM_TYPES.CLASS_DIAGRAM,
    severity: SEVERITIES.WARNING,
    category: RULE_CATEGORIES.NAMING,
    description: 'A class declares the same operation signature more than once',
    messageTemplate: 'Duplicate operation "{op}" on class "{cls}".',
    dependencies: ['CD-002'],
    enabled: true,
  },
  {
    id: 'CD-021',
    code: 'CLASS_INHERITANCE_CYCLE',
    name: 'Circular Inheritance',
    diagramType: DIAGRAM_TYPES.CLASS_DIAGRAM,
    severity: SEVERITIES.ERROR,
    category: RULE_CATEGORIES.STRUCTURAL,
    description: 'An inheritance chain contains a cycle (including self-inheritance)',
    messageTemplate: 'Circular inheritance detected in the class diagram.',
    dependencies: ['CD-002'],
    enabled: true,
  },
  {
    id: 'CD-022',
    code: 'CLASS_RELATIONSHIP_DANGLING',
    name: 'Dangling Class Relationship',
    diagramType: DIAGRAM_TYPES.CLASS_DIAGRAM,
    severity: SEVERITIES.ERROR,
    category: RULE_CATEGORIES.STRUCTURAL,
    description: 'A relationship edge references a class that does not exist',
    messageTemplate: 'Relationship "{type}" references a class that no longer exists.',
    dependencies: ['CD-002'],
    enabled: true,
  },
  {
    id: 'CD-023',
    code: 'CLASS_IMPLEMENTATION_TARGET_NOT_INTERFACE',
    name: 'Realization Target Not Interface',
    diagramType: DIAGRAM_TYPES.CLASS_DIAGRAM,
    severity: SEVERITIES.WARNING,
    category: RULE_CATEGORIES.STRUCTURAL,
    description: 'An implementation/realization edge points at a class rather than an interface',
    messageTemplate: 'Implementation/realization edge targets "{cls}", which is not an interface.',
    dependencies: ['CD-002'],
    enabled: true,
  },
  {
    id: 'SEQ-010',
    code: 'SEQUENCE_OBJECT_NOT_DEFINED',
    name: 'Sequence Lifeline Object Not Defined',
    diagramType: DIAGRAM_TYPES.SEQUENCE_DIAGRAM,
    severity: SEVERITIES.ERROR,
    category: RULE_CATEGORIES.CONSISTENCY,
    description: 'A sequence lifeline object is not defined in the class diagram (replaces deprecated SEQ-005)',
    messageTemplate: 'Lifeline object "{label}" in Sequence Diagram is not defined in the Class Diagram.',
    dependencies: ['CD-002'],
    enabled: true,
  },
  {
    id: 'SEQ-011',
    code: 'SEQUENCE_OPERATION_NOT_DEFINED',
    name: 'Sequence Operation Not Defined',
    diagramType: DIAGRAM_TYPES.SEQUENCE_DIAGRAM,
    severity: SEVERITIES.ERROR,
    category: RULE_CATEGORIES.CONSISTENCY,
    description: 'A sequence message is not declared as an operation on any class (replaces deprecated SEQ-006)',
    messageTemplate: 'Sequence message "{msg}" is not defined as an operation on any class in the Class Diagram.',
    dependencies: ['CD-002'],
    enabled: true,
  },
  {
    id: 'SEQ-012',
    code: 'SEQUENCE_OPERATION_RECEIVER_MISMATCH',
    name: 'Sequence Operation Receiver Mismatch',
    diagramType: DIAGRAM_TYPES.SEQUENCE_DIAGRAM,
    severity: SEVERITIES.WARNING,
    category: RULE_CATEGORIES.CONSISTENCY,
    description: 'A message targets a lifeline whose class does not own the matching operation',
    messageTemplate: 'Sequence message "{msg}" targets lifeline "{receiver}", but the matching operation "{op}" is owned by class "{owner}".',
    dependencies: ['CD-002'],
    enabled: true,
  },
  {
    id: 'SEQ-013',
    code: 'SEQUENCE_DUPLICATE_LIFELINE',
    name: 'Duplicate Sequence Lifeline',
    diagramType: DIAGRAM_TYPES.SEQUENCE_DIAGRAM,
    severity: SEVERITIES.WARNING,
    category: RULE_CATEGORIES.NAMING,
    description: 'The same participant lifeline appears more than once in a sequence diagram',
    messageTemplate: 'Duplicate lifeline "{label}" in Sequence Diagram for "{name}".',
    dependencies: ['SEQ-001'],
    enabled: true,
  },
  {
    id: 'SEQ-014',
    code: 'SEQUENCE_DUPLICATE_MESSAGE',
    name: 'Duplicate Sequence Message',
    diagramType: DIAGRAM_TYPES.SEQUENCE_DIAGRAM,
    severity: SEVERITIES.WARNING,
    category: RULE_CATEGORIES.NAMING,
    description: 'An identical message (same name, sender and receiver) is sent more than once',
    messageTemplate: 'Duplicate message "{msg}" in Sequence Diagram for "{name}".',
    dependencies: ['SEQ-001'],
    enabled: true,
  },
  {
    id: 'SEQ-015',
    code: 'SEQUENCE_MESSAGE_DANGLING_LIFELINE',
    name: 'Sequence Message Dangling Lifeline',
    diagramType: DIAGRAM_TYPES.SEQUENCE_DIAGRAM,
    severity: SEVERITIES.ERROR,
    category: RULE_CATEGORIES.STRUCTURAL,
    description: 'A sequence message references a lifeline that does not exist in the diagram',
    messageTemplate: 'Sequence message "{msg}" references a lifeline that does not exist in the diagram for "{name}".',
    dependencies: ['SEQ-001'],
    enabled: true,
  },
];

const ruleMap = new Map();
rules.forEach((rule) => {
  ruleMap.set(rule.code, rule);
});

function getRuleByCode(code) {
  return ruleMap.get(code) || null;
}

function getRulesByDiagramType(diagramType) {
  return rules.filter((r) => r.diagramType === diagramType);
}

function getRulesByCategory(category) {
  return rules.filter((r) => r.category === category);
}

function getEnabledRules() {
  return rules.filter((r) => r.enabled);
}

function getDependencyChain(ruleId) {
  const rule = rules.find((r) => r.id === ruleId);
  if (!rule) return [];
  const deps = [];
  function resolveDeps(id) {
    const r = rules.find((x) => x.id === id);
    if (r) {
      r.dependencies.forEach((depId) => {
        if (!deps.includes(depId)) {
          resolveDeps(depId);
          deps.push(depId);
        }
      });
    }
  }
  resolveDeps(ruleId);
  return deps;
}

function getAffectedByDependency(ruleId) {
  return rules.filter((r) => r.dependencies.includes(ruleId));
}

module.exports = {
  RULE_CATEGORIES,
  DIAGRAM_TYPES,
  SEVERITIES,
  rules,
  getRuleByCode,
  getRulesByDiagramType,
  getRulesByCategory,
  getEnabledRules,
  getDependencyChain,
  getAffectedByDependency,
};
